/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.AbrirImagen;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import umbralizacionrgb.Histograma;
import umbralizacionrgb.UmbralizarImagen;

/**
 *
 * @author Roberto Cruz Leija
 */
public class Principal extends javax.swing.JFrame {

    BufferedImage imagenOriginal;
    UmbralizarImagen umbralizador;
    boolean jchbAuxRed, jchbAuxGreen, jchbAuxBlue;
    int jsAuxRed1, jsAuxRed2, jsAuxGreen1, jsAuxGreen2, jsAuxBlue1, jsAuxBlue2;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.imagenOriginal = null;
        this.umbralizador = null;
        initValues();
        updateValues();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jCheckBoxRed = new javax.swing.JCheckBox();
        jSliderRed1 = new javax.swing.JSlider();
        jCheckBoxGreen = new javax.swing.JCheckBox();
        jSlideRed2 = new javax.swing.JSlider();
        jCheckBoxBlue = new javax.swing.JCheckBox();
        jSlideGreen1 = new javax.swing.JSlider();
        jSliderGreen2 = new javax.swing.JSlider();
        jSliderBlue1 = new javax.swing.JSlider();
        jSliderBlue2 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextRed1 = new javax.swing.JTextField();
        jTextGreen1 = new javax.swing.JTextField();
        jTextBlue1 = new javax.swing.JTextField();
        jTextRed2 = new javax.swing.JTextField();
        jTextBlue2 = new javax.swing.JTextField();
        jTextGreen2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 500, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jCheckBoxRed.setText("Inside Red ");
        jCheckBoxRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRedActionPerformed(evt);
            }
        });

        jSliderRed1.setMaximum(255);
        jSliderRed1.setPaintLabels(true);
        jSliderRed1.setValue(30);

        jCheckBoxGreen.setText("Inside Green");

        jSlideRed2.setMaximum(255);
        jSlideRed2.setValue(230);

        jCheckBoxBlue.setText("Inside Blue");

        jSlideGreen1.setMaximum(255);
        jSlideGreen1.setPaintLabels(true);
        jSlideGreen1.setValue(30);

        jSliderGreen2.setMaximum(255);
        jSliderGreen2.setValue(230);

        jSliderBlue1.setMaximum(255);
        jSliderBlue1.setPaintLabels(true);
        jSliderBlue1.setValue(30);

        jSliderBlue2.setMaximum(255);
        jSliderBlue2.setValue(230);

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextRed1.setText("jTextField1");
        jTextRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRed1ActionPerformed(evt);
            }
        });

        jTextGreen1.setText("jTextField2");

        jTextBlue1.setText("jTextField3");

        jTextRed2.setText("jTextField4");

        jTextBlue2.setText("jTextField5");

        jTextGreen2.setText("jTextField6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderRed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSlideRed2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSlideGreen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSliderGreen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSliderBlue1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSliderBlue2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 154, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jCheckBoxRed)
                                        .addGap(144, 144, 144)
                                        .addComponent(jTextRed1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jCheckBoxBlue)
                                        .addGap(150, 150, 150)
                                        .addComponent(jTextBlue1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jCheckBoxGreen)
                                        .addGap(144, 144, 144)
                                        .addComponent(jTextGreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextGreen2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextBlue2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextRed2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jTextRed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jCheckBoxRed)
                                .addGap(15, 15, 15)))
                        .addComponent(jSliderRed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextRed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSlideRed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jTextGreen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxGreen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlideGreen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextGreen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jSliderGreen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBlue1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxBlue, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderBlue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTextBlue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderBlue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRedActionPerformed
    }//GEN-LAST:event_jCheckBoxRedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // generamos la imagen original 
            imagenOriginal = AbrirImagen.abrirImagen();
            // mandamos la referencia de la imagen original
            Histograma.imagen = this.imagenOriginal;

            this.jLabelImagen.setIcon(new ImageIcon(imagenOriginal));

            // calcular histogramas 
            this.umbralizador = new UmbralizarImagen(imagenOriginal);
            this.umbralizador.generaFraficoHistograma();
            // detectamos los estados iniciales de los componentes
            this.jchbAuxRed = this.jCheckBoxRed.isEnabled();
            this.jchbAuxGreen = this.jCheckBoxGreen.isEnabled();
            this.jchbAuxBlue = this.jCheckBoxBlue.isEnabled();
            this.jsAuxRed1 = this.jSliderRed1.getValue();
            this.jsAuxRed2 = this.jSlideRed2.getValue();
            this.jsAuxGreen1 = this.jSlideGreen1.getValue();
            this.jsAuxGreen2 = this.jSliderGreen2.getValue();
            this.jsAuxBlue1 = this.jSliderBlue1.getValue();
            this.jsAuxBlue2 = this.jSliderBlue2.getValue();

        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //obtenemos los valores del slider y checkbox
        // canal rojo

        if (this.jchbAuxRed != this.jCheckBoxRed.isEnabled()
                || this.jsAuxRed1 != this.jSliderRed1.getValue()
                || this.jsAuxRed2 != this.jSlideRed2.getValue()) {
            this.umbralizador.actualizarRojo(this.jSliderRed1.getValue(), 
                    this.jSlideRed2.getValue(), 
                    this.jCheckBoxRed.isEnabled());

            // actualizar la imagen 
            this.jLabelImagen.setIcon(new ImageIcon(this.umbralizador.getImagenNueva()));
            // generamos el nuevo grafico 
            this.umbralizador.generaFraficoHistograma();
            // actualizar el estado nuevo 
            this.jchbAuxRed = this.jCheckBoxRed.isEnabled();
            this.jsAuxRed1 = this.jSliderRed1.getValue();
            this.jsAuxRed2 = this.jSlideRed2.getValue();
        }

        if (this.jchbAuxGreen != this.jCheckBoxGreen.isEnabled()
                || this.jsAuxGreen1 != this.jSlideGreen1.getValue()
                || this.jsAuxGreen2 != this.jSliderGreen2.getValue()) {
            this.umbralizador.actualizarVerde(this.jSlideGreen1.getValue(),
                    this.jSliderGreen2.getValue(), this.jCheckBoxGreen.isEnabled());

            // actualizar la imagen 
            this.jLabelImagen.setIcon(new ImageIcon(this.umbralizador.getImagenNueva()));
            // generamos el nuevo grafico 
            this.umbralizador.generaFraficoHistograma();
            // actualizar el estado nuevo 
            this.jchbAuxGreen = this.jCheckBoxGreen.isEnabled();
            this.jsAuxGreen1 = this.jSlideGreen1.getValue();
            this.jsAuxGreen2 = this.jSliderGreen2.getValue();
        }

        if (this.jchbAuxBlue != this.jCheckBoxBlue.isEnabled()
                || this.jsAuxBlue1 != this.jSliderBlue1.getValue()
                || this.jsAuxBlue2 != this.jSliderBlue2.getValue()) {
            this.umbralizador.actualizarAzul(this.jSliderBlue1.getValue(),
                    this.jSliderBlue2.getValue(), this.jCheckBoxBlue.isEnabled());

            // actualizar la imagen 
            this.jLabelImagen.setIcon(new ImageIcon(this.umbralizador.getImagenNueva()));
            // generamos el nuevo grafico 
            this.umbralizador.generaFraficoHistograma();
            // actualizar el estado nuevo 
            this.jchbAuxBlue = this.jCheckBoxBlue.isEnabled();
            this.jsAuxBlue1 = this.jSliderBlue1.getValue();
            this.jsAuxBlue2 = this.jSliderBlue2.getValue();
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRed1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxBlue;
    private javax.swing.JCheckBox jCheckBoxGreen;
    private javax.swing.JCheckBox jCheckBoxRed;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlideGreen1;
    private javax.swing.JSlider jSlideRed2;
    private javax.swing.JSlider jSliderBlue1;
    private javax.swing.JSlider jSliderBlue2;
    private javax.swing.JSlider jSliderGreen2;
    private javax.swing.JSlider jSliderRed1;
    private javax.swing.JTextField jTextBlue1;
    private javax.swing.JTextField jTextBlue2;
    private javax.swing.JTextField jTextGreen1;
    private javax.swing.JTextField jTextGreen2;
    private javax.swing.JTextField jTextRed1;
    private javax.swing.JTextField jTextRed2;
    // End of variables declaration//GEN-END:variables

    private void initValues() {
        this.jTextRed1.setText(""+this.jSliderRed1.getValue());
        this.jTextRed2.setText(""+this.jSlideRed2.getValue());
        this.jTextBlue1.setText(""+this.jSliderBlue1.getValue());
        this.jTextBlue2.setText(""+this.jSliderBlue2.getValue());
        this.jTextGreen1.setText(""+this.jSlideGreen1.getValue());
        this.jTextGreen2.setText(""+this.jSliderGreen2.getValue());
    }

    private void updateValues() {
        jSliderRed1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                jTextRed1.setText(""+jSliderRed1.getValue());
            }
        });
        
        jSlideRed2.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                jTextRed2.setText(""+jSlideRed2.getValue());
            }
        });
        
        jSlideGreen1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                jTextGreen1.setText(""+jSlideGreen1.getValue());
            }
        });
        
        jSliderGreen2.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                jTextGreen2.setText(""+jSliderGreen2.getValue());
            }
        });
        
        jSliderBlue1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                jTextBlue1.setText(""+jSliderBlue1.getValue());
            }
        });
                
        jSliderBlue2.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                jTextBlue2.setText(""+jSliderBlue2.getValue());
            }
        });                
    }
}